### ISSUE TITLE
add trial mode

### ISSUE THREAD

**Issue by chrtze** [xyflow/pro-platform#24]
we want to add a trial mode to the pro platform so that you can see the format of the pro examples. there are two options:

1. we have 1-2 "free" pro examples that everyone can view when they sign up
2. we add a free trial via stripe checkout that gives you access to some examples once you enter the billing details.

**Comment by johnrobbjr** [comment]
What do we name the pill in sidebar in public-facing docs?
- Try Pro
- Free Pro
- Try

**Comment by hayleigh-dot-dev** [comment]
"Pro Trial" or something maybe?

> Which Pro example should be free?

My vote is on copy & paste or expand & collapse.

**Comment by johnrobbjr** [comment]
https://github.com/xyflow/web/tree/faq-pro-trial - branch with updated FAQ for Pro index page
