### ISSUE TITLE
improve markdown rendering

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [xyflow/pro-platform#37]
In the collaborative flow readme, we have this nested list at the beginning:

```md
- [Dependencies](#dependencies)
- [Breakdown](#breakdown)
  - [Setting up yjs](#setting-up-yjs)
  - [The `useNodesStateSynced` hook](#the-usenodesstatesynced-hook)
  - [The `useCursorStateSynced` hook](#the-usecursorstatesynced-hook)
  - [Rendering multiple cursors](#rendering-multiple-cursors)
- [Related docs](#related-docs)
- [See also](#see-also)
```

But it seems to be rendering as a flat list:

![Screenshot 2023-12-14 at 12 41 20](https://github.com/xyflow/pro-platform/assets/9001354/e46e5279-1ae7-4437-aa3b-ff782c9def3f)

**Comment by chrtze** [comment]
also, the links are not working in this case. we need to add ids to the heading elements, too.

**Comment by chrtze** [comment]
+ table support would be a good improvement.
