### ISSUE TITLE
I can't make this project running.

### ISSUE THREAD

**Issue by sikaco** [xyflow/pro-platform#71]
<img width="383" alt="截屏2024-08-23 16 24 56" src="https://github.com/user-attachments/assets/5f2dc1d1-e7d5-4161-b243-06651ef3a570">

Error said `nhost init` or `nhost config pull`, but `nhost.toml` was existed.
So what should I do?

**Comment by sikaco** [comment]
<img width="512" alt="截屏2024-08-23 16 33 03" src="https://github.com/user-attachments/assets/09b7221c-cb10-432c-8357-dea39d4fd063">
Where can I get these .env variables?

**Comment by sikaco** [comment]
@chrtze Excuse me, could you please check this issue?

**Comment by moklick** [comment]
you should be able to run the platform locally by using placeholder secrets like 

```md
DISCORD_NOTIFICATIONS_WEBHOOK='-'
GITHUB_CLIENT_ID='-'
GITHUB_CLIENT_SECRET='-'
GRAFANA_ADMIN_PASSWORD='-'
HASURA_GRAPHQL_ADMIN_SECRET='nhost-admin-secret'
HASURA_GRAPHQL_JWT_SECRET='-'
MAILJET_APIKEY_PRIVATE='-'
MAILJET_APIKEY_PUBLIC='-'
NHOST_WEBHOOK_SECRET='nhost-webhook-secret'
SMTP_PASSWORD='-'
STRIPE_SECRET_KEY='-'
STRIPE_WEBHOOK_SECRET='-'
VERCEL_WEBHOOK_SECRET='-'
GITHUB_ACCESS_TOKEN='-'
UPSTASH_REDIS_URL='-'
UPSTASH_REDIS_TOKEN='-'
```

The platform is not about the React Flow Pro examples (they are also not included in this repo). The platform can be used for inspiration, learning or as a starting point for your own projects.

**Comment by sikaco** [comment]
Got it, thanks replay.

**Comment by sikaco** [comment]
> you should be able to run the platform locally by using placeholder secrets like
> 
> ```
> DISCORD_NOTIFICATIONS_WEBHOOK='-'
> GITHUB_CLIENT_ID='-'
> GITHUB_CLIENT_SECRET='-'
> GRAFANA_ADMIN_PASSWORD='-'
> HASURA_GRAPHQL_ADMIN_SECRET='nhost-admin-secret'
> HASURA_GRAPHQL_JWT_SECRET='-'
> MAILJET_APIKEY_PRIVATE='-'
> MAILJET_APIKEY_PUBLIC='-'
> NHOST_WEBHOOK_SECRET='nhost-webhook-secret'
> SMTP_PASSWORD='-'
> STRIPE_SECRET_KEY='-'
> STRIPE_WEBHOOK_SECRET='-'
> VERCEL_WEBHOOK_SECRET='-'
> GITHUB_ACCESS_TOKEN='-'
> UPSTASH_REDIS_URL='-'
> UPSTASH_REDIS_TOKEN='-'
> ```
> 
> The platform is not about the React Flow Pro examples (they are also not included in this repo). The platform can be used for inspiration, learning or as a starting point for your own projects.

Thanks replay.
